frameworkVersion: ^3.39.0
service: hello
provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
package:
  individually: true
functions:
  hello:
    handler: bin/bootstrap
    package:
      artifact: bin/hello.zip
    events:
      - http:
          path: hello
          method: post